### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by samape** [samape/furima-37831#21]
# URL
https://furima-37831.herokuapp.com/

# Basic認証
ID：furima-admin
Pass：123abc

# 出品者用情報
Mail：test1@hoge.com
Pass：111aaa

# 購入者用情報
Mail：test2@hoge.com
Pass：111aaa

**Comment by motomuun** [comment]
@samape さん、ご提出ありがとうございます‼︎
お送りいただいたBasic認証のIDとパスワードを入力してもアプリを閲覧することができません。
掲載して頂いているIDとパスワードが相違ないか、お手数ですがご確認の上、再度ご提出をお願いします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by samape** [comment]
> @samape さん、ご提出ありがとうございます‼︎ お送りいただいたBasic認証のIDとパスワードを入力してもアプリを閲覧することができません。 掲載して頂いているIDとパスワードが相違ないか、お手数ですがご確認の上、再度ご提出をお願いします。
> 
> 修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！ ※新しいissueを作っていただく必要はございません。 ※質問等でコメントした場合も都度フォームのご提出をお願いします。 https://forms.gle/dYuR1wjeHepbEhU7A

ご確認いただきありがとうございます！
Basic認証のIDに誤りがございました。
お手数お掛けし申し訳ございませんが、改めて報告フォームを提出させていただきます。
引き続きよろしくお願い致します！

**Comment by snkw-works** [comment]
@samape さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```

今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```

※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/curriculums/7106

今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by samape** [comment]
> @samape さん、フリマアプリ達成要件分の開発お疲れ様でした！ 正常に動作することが確認できました！LGTMです！　 おめでとうございます🎉
> 
> **※確認したのは必須機能のみです。追加実装した機能については確認しておりません。 そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。** **※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**
> 
> ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！
> 
> #### ＜今後の学習例＞
> ```
> ・フリマアプリ追加実装
> ・オリジナルアプリ開発
> ・今まで学んできた言語あるいは新言語の学習　等
> ```
> 
> 今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
> 
> また、以下提出物に関するリマインドです。
> 
> #### ＜提出物＞
> ```
> ・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
> ・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
> ```
> 
> ※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。
> 
> #### ＜最終課題に関する締め切りについての動画＞
> https://master.tech-camp.in/curriculums/7106
> 
> 今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
> 
> ![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

ご確認いただき、またLGTMいただきありがとうございました！
提出物の準備とオリジナルアプリの実装を進めていきます。
よろしくお願い致します。
